/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as ImportRouteImport } from './routes/import'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as RecipientsRouteImport } from './routes/recipients'
import { Route as SendRouteImport } from './routes/send'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as LogsJobIdRouteImport } from './routes/logs.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipientsRoute = RecipientsRouteImport.update({
  id: '/recipients',
  path: '/recipients',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsJobIdRoute = LogsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => LogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generate': typeof GenerateRoute
  '/import': typeof ImportRoute
  '/logs': typeof LogsRouteWithChildren
  '/recipients': typeof RecipientsRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/logs/$jobId': typeof LogsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generate': typeof GenerateRoute
  '/import': typeof ImportRoute
  '/logs': typeof LogsRouteWithChildren
  '/recipients': typeof RecipientsRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/logs/$jobId': typeof LogsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generate': typeof GenerateRoute
  '/import': typeof ImportRoute
  '/logs': typeof LogsRouteWithChildren
  '/recipients': typeof RecipientsRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/logs/$jobId': typeof LogsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/generate'
    | '/import'
    | '/logs'
    | '/recipients'
    | '/send'
    | '/settings'
    | '/templates'
    | '/logs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/generate'
    | '/import'
    | '/logs'
    | '/recipients'
    | '/send'
    | '/settings'
    | '/templates'
    | '/logs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/generate'
    | '/import'
    | '/logs'
    | '/recipients'
    | '/send'
    | '/settings'
    | '/templates'
    | '/logs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenerateRoute: typeof GenerateRoute
  ImportRoute: typeof ImportRoute
  LogsRoute: typeof LogsRouteWithChildren
  RecipientsRoute: typeof RecipientsRoute
  SendRoute: typeof SendRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipients': {
      id: '/recipients'
      path: '/recipients'
      fullPath: '/recipients'
      preLoaderRoute: typeof RecipientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$jobId': {
      id: '/logs/$jobId'
      path: '/$jobId'
      fullPath: '/logs/$jobId'
      preLoaderRoute: typeof LogsJobIdRouteImport
      parentRoute: typeof LogsRoute
    }
  }
}

interface LogsRouteChildren {
  LogsJobIdRoute: typeof LogsJobIdRoute
}

const LogsRouteChildren: LogsRouteChildren = {
  LogsJobIdRoute: LogsJobIdRoute,
}

const LogsRouteWithChildren = LogsRoute._addFileChildren(LogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenerateRoute: GenerateRoute,
  ImportRoute: ImportRoute,
  LogsRoute: LogsRouteWithChildren,
  RecipientsRoute: RecipientsRoute,
  SendRoute: SendRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
